name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v5
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}
        toolchain: stable
    - run: cargo build --release --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v4
      with:
        name: phirust-transpiler-windows
        path: target/${{ matrix.target }}/release/phirust-transpiler.exe

  create-release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v5
      with:
        path: artifacts
    - uses: softprops/action-gh-release@v2
      with:
        files: artifacts/phirust-transpiler-windows/phirust-transpiler.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}